### ISSUE TITLE
VersionInfo should support string output

### ISSUE THREAD

**Issue by nerdoc** [k-bx/python-semver#100]
It may seem weird, but the VersionInfo object lacks the "opposite" thing of parsing a SemVer. I just like to have a str output like "3.0.0" from a VersionInfo - this is not implemented.
Wouldn't it be nice to have something like 
```python
def to_str(self):
    return self.format_version(
        self.major, 
        self.minor,
        self.patch,
        self.prerelease,
        self.build
    )
```
So if you have a VersionInfo object you can print out the original/created string again (for saving in a DB e.g.):
```
>>> version = VersionInfo(3, 4, 5)
>>> print(version.to_str())
3.4.5
```

**Comment by kxepal** [comment]
[`str(VersionInfo(3, 4, 5))`](https://github.com/k-bx/python-semver/blob/master/semver.py#L162-L163) should works as expected. Or it doesn't?

**Comment by nerdoc** [comment]
OMG, yes. Sorry for the spam.

**Comment by kxepal** [comment]
No worries (:

**Comment by nerdoc** [comment]
BTW - VersionInfo(3,4,5) is not possible in 2.8.0 (my installed version using pip):
```
TypeError: __new__() missing 2 required positional arguments: 'prerelease' and 'build'
```
You changed a few things in 2.8.1 ;-)

**Comment by kxepal** [comment]
Indeed, that was fixed in https://github.com/k-bx/python-semver/commit/7fdf7b242dd993aa7a0b22821f94379ac8d983d4

@scls19fr how about new release?

**Comment by scls19fr** [comment]
Related issue https://github.com/k-bx/python-semver/issues/98

2.8.1 version is now available
