### ISSUE TITLE
Wrong comparison result when comparing VersionInfo and string

### ISSUE THREAD

**Issue by scls19fr** [k-bx/python-semver#103]
See https://github.com/k-bx/python-semver/issues/102#issuecomment-405467250

**Comment by scls19fr** [comment]
Should we fix this kind of comparison or disallow it?

**Comment by kxepal** [comment]
I think we should fix tuple comparision since that was a regression. Or a breaking change. However, compare with strings wan't declared nor a feature. I'm doubt that we should since what to do if string isn't a semver thing at all?

**Comment by scls19fr** [comment]
If a string isn't a semver and **if** we decide to allow comparison between `VersionInfo` and `string`, `parse` static method should raise

    ValueError: ..... is not valid SemVer string

Anyway, both for tuple and string, whatever the decision is, we should have tests to ensure that it behave the same way for Python 2 and Python 3

**Comment by scls19fr** [comment]
My guess is that one problem is with

        if not isinstance(other, (VersionInfo, dict)):
            return NotImplemented

which doesn't do what it's expected to do, ie raising exception.

We should have

        if not isinstance(other, (VersionInfo, dict)):
            raise NotImplementedError

**Comment by kxepal** [comment]
It depends where this code is placed. If it's in comparison operators that we done that right.

**Comment by ppkt** [comment]
@scls19fr https://docs.python.org/3.6/library/constants.html#NotImplemented

I think this bug might be introduced when we stopped inheriting from Named Tuple in VersionInfo.When comparing VersionInfo with a tuple our operators does not support this but then Python interpreter was trying to reverse the operands (i.e. to compare tuple with VersionInfo) and since VersionInfo was an instance of tuple, it was possible.

In my opinion we could fix this by adding new statement:
```
    if isinstance(other, isinstance(a, collections.abc.Iterable)):
        # compare `other` with tuple representing VersionInfo
    return NotImplemented
```
to every method (`__eq__`, `__le__` and so on).

**Comment by scls19fr** [comment]
I also think it's my fault ;-)
`str` are iterable... but we may not want to compare `VersionInfo` and `str`

**Comment by ppkt** [comment]
Well. in first place inheriting from NamedTuple was a bit hackish attempt to allow comparing VersionInfo with both dict and tuple :)
I'm aware that it's not perfect solution (and it seems that Iterable was introduced only in Python3.6) but I think we can follow this way: https://docs.python.org/2.7/library/collections.html#collections-abstract-base-classes

**Comment by kxepal** [comment]
+1 to not compare with strings. We shouldn't turn ourself into JavaScript (:
