### ISSUE TITLE
Pre-release comparisons incorrect

### ISSUE THREAD

**Issue by aodj** [k-bx/python-semver#107]
According to [item 11](https://semver.org/#spec-item-11) in the spec:

>  When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0.

This doesn't appear to be the case:
```
>>> semver.parse('1.0.0-alpha') < semver.parse('1.0.0')
False
```
This is using version `2.8.1` installed from Pypi

**Comment by aodj** [comment]
That said, the `min_ver` check appears to work correctly:
```
>>> semver.min_ver('1.0.0-alpha', '1.0.0')
'1.0.0-alpha'
```

**Comment by aodj** [comment]
Ah, I think I see my problem; the `parse` method returns a `dict`, and then the comparison is done using the `dict` comparison and not using the logic in the `VersionInfo` object.

I'll close this issue, and hopefully someone else can learn from my mistake ;)

**Comment by ppkt** [comment]
@aodj good catch :)
In your case following code should work as expected:
```
>>> from semver import VersionInfo
>>> VersionInfo.parse('1.0.0-alpha') < VersionInfo.parse('1.0.0')
True
```
