### ISSUE TITLE
Docstring for format_version is wrong

### ISSUE THREAD

**Issue by zgoda-mobica** [k-bx/python-semver#128]
https://github.com/k-bx/python-semver/blob/344ea8902a52b198534e15759925884601ac7509/semver.py#L403-L417

major, minor and patch can not be passed as `str`, despite docstring saying so because format specifier expects integers.

**Comment by scls19fr** [comment]
Hi @zgoda-mobica 

Good catch! Contributions are always welcome.

Best regards
