### ISSUE TITLE
Publish a new release on PyPi (2.9.0)

### ISSUE THREAD

**Issue by scls19fr** [k-bx/python-semver#134]
Thanks to great work of @Flamefire we are now ready to publish a new release on PyPi

Here is a release procedure to follow
https://github.com/k-bx/python-semver/blob/master/release-procedure.md

but maybe we should have a discussion before about version numbering.

I don't really know if this new version should be named 2.8.2 or 2.9.0 (to respect semver)

Your opinions?

PS : I won't be available during the next coming days (until next week) so either @k-bx can publish or we can wait some days.

**Comment by Flamefire** [comment]
Although it is mostly a bugfix release (comparison was broken in last version) it contains a new feature: iterable

So it should be 2.9.0

**Comment by pedrocunha** [comment]
Hi - any plans to release a new version? The documentation does not match the available release on supporting comparison between VersionInfo objects and tuples. Thanks!

**Comment by migueleliasweb** [comment]
Hey all, any updates on this?

**Comment by ofek** [comment]
@k-bx Can you please upload a new release? Many of us are blocked on this 🙁

**Comment by scls19fr** [comment]
Ideally I think the following PR should be merged before (#140 #138 and maybe #146)
We need a PR to prepare this release (see https://github.com/k-bx/python-semver/blob/master/release-procedure.md)
CHANGELOG at least should be updated (it haven't been updated since last release 2.8.1 (9 Jul 2018) which was see https://github.com/k-bx/python-semver/pulls?q=is%3Apr+is%3Aclosed
Contributions are always welcome!

**Comment by tomschr** [comment]
Maybe you want to have PR #147 included in the release as well. :wink:

**Comment by scls19fr** [comment]
Well the problem was that I was in [my master](https://github.com/scls19fr/python-semver)... not [k-bx/python-semver](https://github.com/k-bx/python-semver/) master but there is still a problem.

```
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading semver-2.9.0-py2.py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16.9k/16.9k [00:01<00:00, 9.27kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by Flamefire** [comment]
Maybe easier: Use Markdown?

**Comment by tomschr** [comment]
> Maybe easier: Use Markdown?

The `CHANGELOG.rst` file can't be included into the doc anymore (well, actually you can, but it would be a bit more cumbersome).

**Comment by tomschr** [comment]
> @ofek is right... see #171

Oh really? I wasn't aware of that. Strange that PyPI seems to have problems with this. Couldn't they just ignore the `:func:` directive?

**Comment by scls19fr** [comment]
Doc build wasn't passing correctly.
Now it's fine https://python-semver.readthedocs.io/en/latest/

**Comment by tomschr** [comment]
@scls19fr Thanks you for all your efforts! :+1:

**Comment by scls19fr** [comment]
Thanks all! I think we still need to improve the release procedure to have smoother release.
#173 

Automatic build of doc should also be on our top 1 priority list (#95)

**Comment by tomschr** [comment]
> I think we still need to improve the release procedure to have smoother release.

Maybe [Git Actions](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-actions) could help?

**Comment by tomschr** [comment]
Maybe I can try something, but it takes some time.

**Comment by tomschr** [comment]
@scls19fr I've created a GitHub Action for my forked repo. Seems it works for me. :wink: 

* Pull Request
  https://github.com/tomschr/python-semver/pull/1
* See the GitHub Action
  https://github.com/tomschr/python-semver/commit/e82151e7fccb56524d3644b64fd1d22c04380005/checks?check_suite_id=289701678

If you want to use it, you need to do these steps:

1. Enable/register/whatever these GitHub Actions for your repo.
1. Add your secrets for PyPI.org and test.pypi.org to your GitHub settings > Secrets.
    Keep in mind, the names must be `test_pypi_password` and `pypi_password`.
1. Remove the comments in `.github/workflow/publish-to-test-pypi.yml` (should we use a better name?)

I've followed mostly the examples mentioned in https://github.com/k-bx/python-semver/issues/134#issuecomment-547974120.

Let me know what you think. :wink:

**Comment by scls19fr** [comment]
I haven't access to "settings" in this repository.
I think we should either ask @k-bx to do it or fork this repository in a GitHub organization where we could do that.
@tomschr @k-bx what are your opinions?

**Comment by tomschr** [comment]
@scls19fr 
Thanks for your response and asking for my opinion. I'm not sure if I can be of any value to this issue, so I'm fine with whatever you decide.

These GitHub Actions, once enabled, can be basically changed by everyone with a simple pull request (it's just the `.github/workflow/` directory).

**Comment by scls19fr** [comment]
I've created https://github.com/python-semver GH org and sent an invite to @k-bx to be an owner.
I'm waiting for an answer before going beyond.

**Comment by k-bx** [comment]
Hey, sure, feel free to move into an organization. Also, please ping me by my email directly if I'm needed, I'm rarely reading the github issues.

**Comment by tomschr** [comment]
@scls19fr @k-bx  Maybe you know that already so sorry to bother. With a GitHub organization you can group trusted members into different teams which different permissions (an author team has write/push permission, but cannot change admin settings, but an admin team can).

This may be a start:

* [Organizing members into teams](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/organizing-members-into-teams)
* [Managing team access to an organization repository](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-team-access-to-an-organization-repository)

**Comment by scls19fr** [comment]
Hi all,

Thanks @k-bx for accepting the idea of a GH org.
This should greatly help collective maintenance work on python-semver!

In order to keep issues history, I think you will need to transfer ownership of https://github.com/k-bx/python-semver to https://github.com/python-semver/ Github org.

https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

Kind regards
