### ISSUE TITLE
Improve Description on PyPI

### ISSUE THREAD

**Issue by tomschr** [k-bx/python-semver#154]
## Situation

The project description on https://pypi.org/project/semver/ is a bit short. Although there is a link to the documentation, people could miss it and be mislead that the project is "undocumented", in a alpha state etc.

## Proposed Solution

When developers search for something, we should support them with at least some small hints. I consider this as cheap and easy "marketing the project" in the sense of attracting people instead of repelling them. Let's make our project shine! :wink: 

Probably it's enough to insert some small information into the `README.rst`. The information could contain a small "session" how to work with it:

* Import the module
* Parse a version string
* Access the different parts of a version

Probably that would be enough to get the attention of the reader. For details, we can refer to our documentation.

**Comment by ppkt** [comment]
@tomschr great idea, I think we have such thing already thanks to you: https://github.com/k-bx/python-semver/blob/master/docs/usage.rst :)
I'm not an expert in Markdown, but maybe there is a possibility to "include" this file in Readme to avoid copy / paste the same code.

**Comment by tomschr** [comment]
Hehe, yes, I know the author. :smile: 
My idea would be a kind of "quick start", maybe it can be included into the main documentation. Let me check.

**Comment by tomschr** [comment]
@ppkt 
> I'm not an expert in Markdown, but maybe there is a possibility to "include" this file in Readme to avoid copy / paste the same code.

I did exactly this. :-) Although some parts are already described in the usage section, you probably can't really avoid some duplication. Well, let's see if I find a better approach tomorrow. :wink:
