### ISSUE TITLE
Consider different format of the Changelog

### ISSUE THREAD

**Issue by tomschr** [k-bx/python-semver#159]
## Situation

(sorry for this longer text)

Currently, changes to semver are covered in the `CHANGELOG` file. That's good. It contains the date of the released version and a list of issues, for example:

```
Version 2.8.1
=============
:Released: 2018-07-09
:Maintainer: Sébastien Celles <s.celles@gmail.com>

* Issue #77 (PR #47). Convert multiple tests into pytest.mark.parametrize
* Issue #89 (PR #90). Add doctests.
* Issue #40 (PR #88). Add a static parse method to VersionInfo
* Issue #87 #94 (PR #93). Remove named tuple inheritance. Fix bad rendering in Pandas DataFrame
* Issue #96 (PR #97). Make VersionInfo immutable
* Issue #98 (PR #99). prerelease and build set to None by default
```

However, IMHO, this format is unfortunate for the following reasons:

* **It's not structured.**
 The issues are not grouped. For example, deprecated functions, new features, bug fixes, and security issues etc. Having a dedicated sections would improve readability.
* **It hides information.**
  As we don't have groups, important information can be hidden which are essential for packagers (maintenance release cycle) or interested customers. Both need to know if an update introduces any regressions, change existing behavior, or add new features.
* **It's not (entirely) RST.**
  As it's not RST, we can't include it in our documentation.
  I think, this is important: The reader should have everything inside the documentation. People shouldn't be forced to switch back to the repository, open the `CHANGELOG` file just to read about what has been changed during the last versions.
* **It's tense/wording is inappropriate**
  If you follow the Git commit style guide, you write commit messages usually as "Add abc" or "Fix issue 123" **(present tense)**.
  However, in changelog entries you write about something that has been *finished in the past*. As such, it needs to be written as "Added abc" or "Fixed issue 123" **(past tense)**.

## Suggested Idea

I know, this can be a controversial topic and people have different "tastes". My intention is just to give an idea or impulse so we can discuss *if* there is a need for this issue, if we should improve the changelog and---if yes---*how*. :-)

First of all, I believe what https://keepachangelog.com writes is true about who needs a changelog (emphasis by me):

> **People do**. Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how. 

### Suggested actions

To reach this goal, my proposal would be to do these steps:

* [x] rename file `CHANGELOG` to `CHANGELOG.rst` to make it easier to include it into documentation.
* [x] if needed, adjust or adapt existing changelog file to adhere to the RST syntax.
* [x] discuss and introduce new groups.
* [x] sort entries into groups.
* [x] optionally, rework existing entries?
     maybe we can leave it as is and just use the new format in the next released? Not sure about this.

Regarding the groups, that depends on what we prefer. For example, https://keepachangelog.com suggest the following "types of changes":

* Added for new features.
* Changed for changes in existing functionality.
* Deprecated for soon-to-be removed features.
* Removed for now removed features.
* Fixed for any bug fixes.
* Security in case of vulnerabilities.

Is that too much? Maybe for this project we can restrict it to the groups "Deprecation", "New Features", and "Bug Fixes"?

### Tips to reduce the workload

* Use a [GitHub Project board](https://help.github.com/en/articles/creating-a-project-board)
  In one of my projects I've created such project board. You can organize your issues and assign them a specific version (or in GH slang "milestone"). This makes organizing versions a bit easier. 
  Additionally, it gives your users the idea what issues goes into what versions, the status of them, and the percentage of the finished issues for a milestone.

* Create [labels](https://help.github.com/en/articles/creating-a-label)
  You could create new labels for your repository, for example "bug", "feature", "doc" etc. Whenever you look into an issue, you can assign a label. In combination with the GitHub project board, it makes it very easy to sort issues into these groups.
  Additionally, GitHub allows to sort your issues by labels.

* Create a [GitHub issue template](https://help.github.com/en/articles/creating-issue-templates-for-your-repository)
  With the help of issue templates, you can make the distinction between bug and feature request when the users creates a new issue.

* Avoid autogenerating entries
  Some projects try to autogenerate entries for the changelog. It could work, but it comes with a price tag: you need to enforce a very strict commit message policy. As we all write commit messages slightly different, I think, that does more harm than good. Some tasks, although maybe uncomfortable, needs be better done manually.
  Why is this entry a "tip"? Because relying on software that generates a changelog is the same than believing a API documentation is a replacement for a good user documentation. :wink:

---

What do you think?

## See also
 
* A good changelog: https://docs.pytest.org/en/latest/changelog.html
* Some further tips: https://depfu.com/blog/what-makes-a-good-changelog

**Comment by scls19fr** [comment]
@tomschr when I read you I see that you are definitely a documentation professional!

I totally agree with you... autogenerating changelog entries does more harm than good.

I just want to let you know that you are 100% free to continue to provide us help by sending PR! (You ever did a lot recently for this project!)

100% agree to rename CHANGELOG to CHANGELOG.rst with reStructuredText

Tagging issues could help.

@k-bx could you allow @tomschr to tag issues?

On my side I have never used GH project board

**Comment by tomschr** [comment]
@scls19fr 

> you are definitely a documentation professional!

Haha, thank you. :+1:  Yes, that's true, I write documentation in my professional live so I naturally take care of it. I also love to write Python programs, so I think the combination is a good fit. That's why I've bothered you all with so many pull requests. :wink: 

> On my side I have never used GH project board

It could be useful for some projects as it helps to organize issues. Not sure if this is something for *this* project. At least it gives *me* a good overview what issue I need to take care of.

Here is an example in one of my repositories. It shows already released versions:

  https://github.com/openSUSE/rstxml2docbook/milestones?state=closed

As you can see, all of them are 100% complete and each issue belongs to a certain milestone. A milestone/version which is not complete is shown here:

  https://github.com/openSUSE/rstxml2docbook/milestone/4

Here you can see, it's finished only by 22%. It gives me a nice overview and where I stand in regards of completeness. Maybe something for this project too?

---

I know my tips does not help for the next release, but it may lower the barrier for upcoming releases. This is what I experienced in my daily work, so your background may vary.

I'm totally fine if others think some of my ideas are not appropriate for this project or don't agree with my suggestions.
