### ISSUE TITLE
ValueError: ~2.0.1 is not valid SemVer string

### ISSUE THREAD

**Issue by brianjmurrell** [k-bx/python-semver#19]
Is this module not up to the latest standard of semver?

**Comment by k-bx** [comment]
I'm not aware of any test-set to check compatibility with latest standard.
Bug-teports and pull-requests are welcome!
18 вер. 2015 22:27 "Brian J. Murrell" <notifications@github.com> пише:

**Comment by brianjmurrell** [comment]
Yeah.  I think the problem is that ~ is not actually part of semver but just part of npm's implementation.  Sorry for the noise.

**Comment by k-bx** [comment]
No problem. I don't mind adding npm version tools if none exists and
someone will make a nice PR :)
18 вер. 2015 22:50 "Brian J. Murrell" <notifications@github.com> пише:
