### ISSUE TITLE
AFAIK `v1.0.0` is proper semver, too

### ISSUE THREAD

**Issue by ghost** [k-bx/python-semver#31]
But optional `v` in the beginning is not taken into account.

**Comment by k-bx** [comment]
Good catch. PR fixing this is welcome! ;)

**Comment by bignose-debian** [comment]
> optional v in the beginning is not taken into account.

The [SemVer 2.0.0 specification](http://semver.org/#semantic-versioning-specification-semver) requires the version string start with the “MAJOR” component, which must be one of the “non-negative integers”.

I don't know the basis for the claim that a leading “v” is allowed; my reading of the specification, to the contrary, says that is prohibited.

**Comment by k-bx** [comment]
@bignose-debian thanks for re-checking. Closing for now then.
