### ISSUE TITLE
Regexp allows invalid prerelease identifiers

### ISSUE THREAD

**Issue by janslow** [k-bx/python-semver#32]
The string `1.2.3-01` in not a valid semantic version (because it has a leading zero in the prerelease identifiers). See http://semver.org/#spec-item-9.

**Comment by k-bx** [comment]
@janslow  thanks for spotting. PRs are welcome!

**Comment by bignose-debian** [comment]
My suggested implementation to address this issue is in the branch at https://pagure.io/python-semver/commits/wip/issue/strict-semver-parsing

**Comment by k-bx** [comment]
@bignose-debian would you please add a test for this? Thank you.

**Comment by bignose-debian** [comment]
On 19-Oct-2016, Kostiantyn Rybnikov wrote:
> @bignose-debian would you please add a test for this? Thank you.

Done now, I've updated the branch with my changes.

-- 
 \     “I used to think that the brain was the most wonderful organ in |
  `\   my body. Then I realized who was telling me this.” —Emo Philips |
_o__)                                                                  |
Ben Finney <ben@benfinney.id.au>

**Comment by k-bx** [comment]
@bignose-debian thanks, released under 2.7.0!

**Comment by k-bx** [comment]
@bignose-debian did you run the tests? They are failing on both python 2 and 3. I hoped you did.

**Comment by k-bx** [comment]
Should be fixed in 2.7.1

**Comment by bignose-debian** [comment]
On 20-Oct-2016, Kostiantyn Rybnikov wrote:
> @bignose-debian did you run the tests? They are failing on both
> python 2 and 3. I hoped you did.

I tested the documentation examples using ‘doctest’.

Until you prompted me, I had not even noticed the unit test module :-)
so no, I didn't run those tests on these changes.

Maybe you'd like to write a document (e.g. named ‘HACKING’) that helps
potential hackers know what you'd like done before proposing some code?

-- 
 \       “If you always want the latest and greatest, then you have to |
  `\          buy a new iPod at least once a year.” —Steve Jobs, MSNBC |
_o__)                                             interview 2006-05-25 |
Ben Finney <ben@benfinney.id.au>

**Comment by k-bx** [comment]
It would probably contain a "make PRs through github, please, so that Travis can test on 6 different Python versions before merging" :)

**Comment by bignose-debian** [comment]
On 20-Oct-2016, Kostiantyn Rybnikov wrote:
> It would probably contain a "make PRs through github, please, so
> that Travis can test on 6 different Python versions before merging"
> :)

Heh. I would not be able to follow those instructions then; Git is
already federated, so I won't be publishing work on centralised GitHub
:-)

-- 
 \           “I just got out of the hospital; I was in a speed-reading |
  `\     accident. I hit a bookmark and flew across the room.” —Steven |
_o__)                                                           Wright |
Ben Finney <ben@benfinney.id.au>
