### ISSUE TITLE
Add majorize/minorize

### ISSUE THREAD

**Issue by sagikazarmark** [k-bx/python-semver#33]
I have the following functions in my helper library:

``` python
def majorize(version):
    version_info = semver.parse(version)
    return "%d" % (version_info["major"])

def minorize(version):
    version_info = semver.parse(version)
    return "%d.%d" % (version_info["major"], version_info["minor"])
```

Although it assumes that the relevant versions are available, would you accept a PR for adding these functions?

**Comment by k-bx** [comment]
@sagikazarmark sorry, I don't see a benefit of having them in the lib so far. Names `majorize` and `minorize` are a bit misleading imho, and it would be rather unclear on what they do, while adding more stuff into the namespace. I'd suggest just keeping them in your helper library, shouldn't be a big deal. Thanks!
