### ISSUE TITLE
Describe every released version in a change log document.

### ISSUE THREAD

**Issue by bignose-debian** [k-bx/python-semver#34]
Version strings are human-facing markers for released versions. The notable changes of a code base should be described for each released version.

My suggested changes for a complete change log document is in the [wip/feature/changelog branch](https://pagure.io/python-semver/branch/wip/feature/changelog) at my personal fork repository.

**Comment by k-bx** [comment]
@bignose-debian looks good. Do you intend to make more progress there or is it ready to be merged?

**Comment by bignose-debian** [comment]
On Thu, 2016-08-25 00:37 -0700, Kostiantyn Rybnikov
<notifications@github.com> wrote:
> @bignose-debian looks good. Do you intend to make more progress there or
> is it ready to be merged?

I keep the “wip” prefix to signal that it may be re-based (for example
if you requested changes before merging).

If you're happy with it as is, please merge.

-- 
 \
  `\
_o__) Ben Finney <ben+python@benfinney.id.au>

**Comment by k-bx** [comment]
@bignose-debian merged, thanks!
