### ISSUE TITLE
Record each maintainer and significant contributor in a document

### ISSUE THREAD

**Issue by bignose-debian** [k-bx/python-semver#35]
My suggestion for a Contributors document is in the [wip/feature/contributors branch](https://pagure.io/python-semver/commits/wip/feature/contributors) of my personal fork repository.

**Comment by k-bx** [comment]
@bignose-debian thanks, looks good. As with previous one (since branch is named "wip"), is it looking good or would you like to do more work?

**Comment by bignose-debian** [comment]
On Thu, 2016-08-25 00:38 -0700, Kostiantyn Rybnikov
<notifications@github.com> wrote:
> @bignose-debian thanks, looks good. As with previous one (since branch is
> named "wip"), is it looking good or would you like to do more work?

I keep the “wip” prefix to signal that it may be re-based (for example
if you requested changes before merging).

If you're happy with it as is, please merge.

-- 
 \
  `\
_o__) Ben Finney <ben+python@benfinney.id.au>

**Comment by k-bx** [comment]
Also merged, thank you!
