### ISSUE TITLE
Parse a version string to a version info tuple

### ISSUE THREAD

**Issue by bignose-debian** [k-bx/python-semver#36]
The Python standard library provides a convention of a “version info tuple”, e.g. the `sys.version_info` tuple.

Please add a feature to parse a version string to a named tuple of the components.

**Comment by bignose-debian** [comment]
My suggested implementation of this feature is in the branch at https://pagure.io/python-semver/commits/wip/feature/make-version-info

**Comment by k-bx** [comment]
@bignose-debian thank you for the proposed implementation! I don't see the repo address on that page to add it into my git remote, what would it be? Branch name is `wip/feature/make-version-info`, I suppose.

**Comment by bignose-debian** [comment]
@k-bx at the “Overview” page for the repository, you can see the “Source Git URLs” for the repository via SSH or HTTPS.

**Comment by k-bx** [comment]
Merged, thank you!

**Comment by k-bx** [comment]
Hmm, travis got broken, reopening for now https://travis-ci.org/k-bx/python-semver/builds/169138646

**Comment by k-bx** [comment]
Fixed.
