### ISSUE TITLE
Remove trailing zeros from prelease doesn't allow to parse 0 pre-release version

### ISSUE THREAD

**Issue by werwolfby** [k-bx/python-semver#37]
This was broken by: https://github.com/k-bx/python-semver/commit/69e9125cfe3dc1537163ffbd4fdfe9c09025b686

By standart [semver](http://semver.org/#spec-item-9):

> Numeric identifiers MUST NOT include leading zeroes.

But 0 value doesn't have leading zeros.

**Steps to reproduce:**
Try to parse ```1.0.0-rc.0```

**Actual behavior:**
It fails

**Expected behavior:**
```1.0.0-rc.0``` should be parsed

**Comment by k-bx** [comment]
@werwolfby thanks for catching this! Would you care enough to fix this? Would appreciate a lot. Thanks!

**Comment by werwolfby** [comment]
Sure! Will do it today.

**Comment by k-bx** [comment]
@werwolfby thank you! Please make sure to add a test case for `1.0.0-rc.0`

**Comment by werwolfby** [comment]
How we can trust changes without test? :)
Of course I'll add tests.
