### ISSUE TITLE
semver-object

### ISSUE THREAD

**Issue by Thor77** [k-bx/python-semver#40]
In my opinion your approach to parsing is quite "unpythonic", I would prefer smth like this:
```py
info = semver('1.0.0')
```
that would allow easy comparison with
```py
>> semver('1.0.0') > semver('2.0.0')
>> False
```
(yes I know there's `semver.compare` for that)
Python is a object-orientated language after all ;)

**Comment by k-bx** [comment]
@Thor77 you can already do that:

```
In [3]: info1 = semver.parse_version_info('1.0.0')

In [4]: info2 = semver.parse_version_info('2.0.0')

In [5]: info1 > info2
Out[5]: False
```

**Comment by Thor77** [comment]
I know there are already ways to accomplish this in your library, but they're verbose and not object-orientated.
For example
```py
ver = semver.parse_version_info('1.0.0')
ver.bump_{major,minor,patch}()
```
does not work.

**Comment by k-bx** [comment]
@Thor77 ah, I see what you mean. So, if you want to make a nice PR implementing a Semver class with all the object-oriented functionality, I wouldn't mind accepting it :)

**Comment by scls19fr** [comment]
@Thor77 I think after PR #88 and #141 we can close this (quite old) issue!
Please feel to reopen if you think that's necessary.
