### ISSUE TITLE
Description is broken on PyPI

### ISSUE THREAD

**Issue by bittner** [k-bx/python-semver#48]
For some reason the [package description on PyPI](https://pypi.python.org/pypi/semver) is broken.

According to [setup.py](https://github.com/k-bx/python-semver/blob/master/setup.py#L77) the [content of README.rst](https://raw.githubusercontent.com/k-bx/python-semver/master/README.rst) is uploaded, provided the package is released using the usual
``` bash
$ python setup.py sdist upload
```
This doesn't seem to have been the case with the last (or last few) release(s).

**Comment by k-bx** [comment]
I use `python setup.py sdist bdist_wininst upload` to upload. Not sure why the description is not being uploaded properly :/

**Comment by bittner** [comment]
The content actually matches the README from the badges on. Only the garbage above the badges is there by error:

> Python helper for Semantic Versioning (http://semver.org/) Examples: >>> import semver >>> semver.compare("1.0.0", "2.0.0") -1 >>> semver.compare("2.0.0", "1.0.0") 1 >>> semver.compare("2.0.0", "2.0.0") 0 >>> semver.match("2.0.0", ">=1.0.0") True >>> semver.match("1.0.0", ">1.0.0") False >>> semver.format_version(3, 4, 5, 'pre.2', 'build.4') '3.4.5-pre.2+build.4' >>> version_parts = semver.parse("3.4.5-pre.2+build.4") >>> version_parts == { ... 'major': 3, 'minor': 4, 'patch': 5, ... 'prerelease': 'pre.2', 'build': 'build.4'} True >>> version_info = semver.parse_version_info("3.4.5-pre.2+build.4") >>> version_info VersionInfo(major=3, minor=4, patch=5, prerelease='pre.2', build='build.4') >>> version_info.major 3 >>> version_info > (1, 0) True >>> version_info < (3, 5) True >>> semver.bump_major("3.4.5") '4.0.0' >>> semver.bump_minor("3.4.5") '3.5.0' >>> semver.bump_patch("3.4.5") '3.4.6' >>> semver.max_ver("1.0.0", "2.0.0") '2.0.0' >>> semver.min_ver("1.0.0", "2.0.0") '1.0.0'

Not sure what it is, really, and where it comes from. You haven't edited the package description manually on PyPI, have you?  -- Then it's maybe a side-effect of `bdist_wininst`, but that seems strange to me ...

**Comment by bittner** [comment]
Oough, found it! It's the [docstring](https://github.com/k-bx/python-semver/blob/master/semver.py#L2-L41) in the module.

You should replace it by simply a one-liner describing the purpose of the module, e.g.
``` python
"""
A Python module for semantic versioning. Simplifies comparing versions.
"""
```

**Comment by k-bx** [comment]
@bittner I see. Thanks for figuring that out, fixed!
