### ISSUE TITLE
server does not recognize major.minor only versions

### ISSUE THREAD

**Issue by fafhrd91** [k-bx/python-semver#51]
for example "1.14" does not work

**Comment by ppkt** [comment]
I believe it's a correct behavior according to semver documentation: http://semver.org/#spec-item-2. In your case, instead of 1.14, you should use 1.14.0.

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

**Comment by fafhrd91** [comment]
ok, thanks
