### ISSUE TITLE
Complex filters

### ISSUE THREAD

**Issue by kpcyrd** [k-bx/python-semver#52]
hi, I'm trying to use python-semver for more complex comparison :)

```
>>> semver.match('6.2.3', '>=6,<6.2.1|>=4.0.0-rc2,<4.2.4|>=5,<5.3.1')
```
which should match according to the rules [composer][1] does it. This is obviously currently not supported but I would really love it to have a method for something like this :)

[1]: https://getcomposer.org/

**Comment by k-bx** [comment]
Hi! You can use a simple Python operators meanwhile to combine comparisons, but I wouldn't mind having a separate API for parsing something like this.

Care to make a PR?

**Comment by kpcyrd** [comment]
@k-bx I've hacked together a bunch of code to parse it successfully, I'm trying to clean it up.

Since you're the author of an semver parser, how should I handle `>=6`?

This currently causes an exception because it's not valid semver and I currently translate it to `>=6.0.0`, which I'm not sure is correct. Do you have an opinion on this?

**Comment by k-bx** [comment]
Yeah. My opinion is — need to make sure semver code is strictly following semver spec, and having the rest additional functionality kept separate and clearly stating that :)

**Comment by scls19fr** [comment]
@kpcyrd may you should ask at https://github.com/semver/semver to improve semver specification to add this concept of complex comparison.
When a "standard" will emerge we will happily accept PR about it.
