### ISSUE TITLE
How to get string from VersionInfo?

### ISSUE THREAD

**Issue by nowox** [k-bx/python-semver#68]
I have a Git tag `v2.0.0` that I want to use in semver and add the commit build to it. Eventually I want to get `2.0.0+2ab23f4`. 

Ideally I would like to write this:

```
>>> import semver
>>> tag = 'v2.0.0'
>>> v = semver.parse_version_info(tag)
>>> v.bump_build('2ab23f4')
>>> str(v)
2.0.0+2ab23f4
```

Unfortunately `VersionInfo` is not a semver class which has no methods such as to-string. 

How should I write this using semver?

**Comment by ppkt** [comment]
Hi,
You could achieve this by following code:
```
>>> import semver
>>> v = semver.parse('2.0.0')
>>> v['build'] = '2ab23f4'
>>> semver.format_version(**v)
'2.0.0+2ab23f4'
```

**Comment by k-bx** [comment]
Thanks @ppkt
