### ISSUE TITLE
VersionInfo string representation

### ISSUE THREAD

**Issue by smarie** [k-bx/python-semver#72]
It seems that the string representation is not available from `VersionInfo`. It should be quite straightforward to do with a custom string representation method:

```python
def __str__(self) -> str:
    return (str(version.major) or '') \
           + (('.' + str(version.minor)) if version.minor is not None else '') \
           + (('.' + str(version.patch)) if version.patch is not None else '') \
           + (('-' + str(version.prerelease)) if version.prerelease is not None else '') \
           + (('+' + str(version.build)) if version.build is not None else '')
```

Note that we can keep `__repr__` untouched so that it provides unambiguous representation.

**Comment by scls19fr** [comment]
`__hash__` should also be implemented #73 (probably with a similar method)
