### ISSUE TITLE
Release 2.8.0

### ISSUE THREAD

**Issue by scls19fr** [k-bx/python-semver#79]
Hello,

Like I said in #78 we need to define a release procedure.
I'm considering the following expected features and changelog (when PR merged)

https://github.com/scls19fr/python-semver/blob/402984a04efbba1c2c3b670fcd9c6869b8429063/CHANGELOG

A possible release procedure (in a `release-procedure.md` file) could be as defined in https://github.com/k-bx/python-semver/pull/81

Any comment?

**Comment by k-bx** [comment]
LGTM

**Comment by scls19fr** [comment]
Will do tomorrow afternoon

**Comment by scls19fr** [comment]
Github release tag https://github.com/k-bx/python-semver/releases/tag/2.8.0

**Comment by scls19fr** [comment]
https://pypi.org/project/semver/ is updated.

FYI, I modified my `.pypirc`

from

```
[distutils] # this tells distutils what package indexes you can push to
index-servers = pypi
    pypi # the live PyPI
    pypitest # test PyPI

[pypi]
repository:https://upload.pypi.org/legacy/
username:mypypi_login
password:*******

[pypitest]
repository:https://test.pypi.org/legacy/
username:mypypi_login
password:*******
```

to

```
[distutils] # this tells distutils what package indexes you can push to
index-servers = pypi
    pypi # the live PyPI
    pypitest # test PyPI

[pypi]
repository:http://pypi.python.org/pypi
username:mypypi_login
password:*******

[pypitest]
repository:https://testpypi.python.org/pypi
username:mypypi_login
password:*******
```
