### ISSUE TITLE
Improve "how to contribute" section

### ISSUE THREAD

**Issue by scls19fr** [k-bx/python-semver#85]
This section need some improvements.

For example we need to clearly explain that:

- only code respecting spec from https://semver.org/ will be merged

- if a contributor want a specific feature which is not currently defined in https://semver.org/ he should probably ask at https://github.com/semver/semver where

Defining a code of conduct may be something useful also.

Other ideas?

**Comment by scls19fr** [comment]
https://coverage.readthedocs.io/en/coverage-4.5.1/ can help

Online services such as
https://coveralls.io/ or https://codecov.io/ also

https://landscape.io/ have nice code metrics

You right, expecting 100% for any code metrics (even code coverage) must not be a goal in itself and contributions that make it very slightly lower are not problematic

**Comment by scls19fr** [comment]
We should inform contributors that an entry in https://github.com/k-bx/python-semver/blob/master/CHANGELOG should be added when submitting a PR.
Changelog entries, having both issue number and PR number, It's a good way to encourage them to first open an issue describing the problem where discussion can take place and only after this, submit a pull request.

**Comment by tomschr** [comment]
> We should inform contributors that an entry in https://github.com/k-bx/python-semver/blob/master/CHANGELOG should be added when submitting a PR.

I'm not sure if this requirement would be useful. For example, I haven't thought about that in my PRs. IMHO, changelog entries should be separate from features.

Shouldn't this be the task of the "release manager" (=the person who creates the release)? He maybe has a better overview and he can  guarantee also some consistency.
